git:
  autoFetch: false
  overrideGpg: true
  pagers:
    - pager: delta --paging=never --hyperlinks --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"
services:
  'tobey': 'github:github.com'
  'squads': 'github:github.com'
gui:
  nerdFontsVersion: "3"
  theme:
    activeBorderColor:
      - "#7aa2f7"
      - "bold"
    inactiveBorderColor:
      - "#a9b1d6"
    searchingActiveBorderColor:
      - "#7aa2f7"
      - "bold"
    optionsTextColor:
      - "#7aa2f7"
    selectedLineBgColor:
      - "#292e42"
    cherryPickedCommitFgColor:
      - "#7aa2f7"
    cherryPickedCommitBgColor:
      - "#3b4261"
    markedBaseCommitFgColor:
      - "#7aa2f7"
    markedBaseCommitBgColor:
      - "#3b4261"
    unstagedChangesColor:
      - "#db4b4b"
    defaultFgColor:
      - "#a9b1d6"
