#!/bin/sh

PLUGIN_DIR="$CONFIG_DIR/plugins"

BG=0xff1a1b26
FG=0xffa9b1d6
DIM=0xff62667e

FONT="JetBrainsMono Nerd Font"
ICON_FONT="JetBrainsMono Nerd Font Mono:Regular:14.0"
LARGE_ICON_FONT="JetBrainsMono Nerd Font Mono:Regular:20.0"
TEXT_FONT="$FONT:Regular:12.0"

sketchybar --bar position=top \
                   height=26 \
                   margin=0 \
                   blur_radius=0 \
                   shadow=off \
                   color="$BG" \
                   notch_width=200 \
                   padding_left=16 \
                   padding_right=16

default=(
  padding_left=0
  padding_right=0
  icon.font="$ICON_FONT"
  icon.color="$FG"
  icon.padding_left=0
  icon.padding_right=0
  label.font="$TEXT_FONT"
  label.color="$FG"
  label.padding_left=0
  label.padding_right=0
  background.drawing=off
)
sketchybar --default "${default[@]}"

sketchybar --add event aerospace_workspace_change

for workspace in 1 2 3 4 5 6 7 8 9; do
  sketchybar --add item "space.$workspace" left \
             --set "space.$workspace" width=20 \
                                      icon="$workspace" \
                                      icon.color="$DIM" \
                                      icon.padding_left=0 \
                                      icon.padding_right=0 \
                                      label.drawing=off
done

for workspace in A B C D E F G H I J K L M N O P Q R S T U V W X Y Z; do
  sketchybar --add item "space.$workspace" left \
             --set "space.$workspace" width=20 \
                                      drawing=off \
                                      icon="$workspace" \
                                      icon.color="$FG" \
                                      icon.padding_left=0 \
                                      icon.padding_right=0 \
                                      label.drawing=off
done

sketchybar --add item workspace_observer left \
           --subscribe workspace_observer aerospace_workspace_change \
           --set workspace_observer width=0 \
                                    update_freq=2 \
                                    icon.drawing=off \
                                    label.drawing=off \
                                    script="$PLUGIN_DIR/space.sh"

sketchybar --add item status.battery right \
           --set status.battery icon=󰁹 icon.font="$ICON_FONT" icon.padding_left=3 icon.padding_right=3 label.drawing=off \
           --add item status.volume right \
           --set status.volume icon=󰕾 icon.font="$LARGE_ICON_FONT" icon.padding_left=3 icon.padding_right=3 label.drawing=off \
           --add item status.network right \
           --set status.network icon=󰖩 icon.font="$LARGE_ICON_FONT" icon.padding_left=3 icon.padding_right=3 label.drawing=off \
           --add item status.bluetooth right \
           --set status.bluetooth icon=󰂯 icon.font="$ICON_FONT" icon.padding_left=3 icon.padding_right=3 label.drawing=off \
           --add item status_observer right \
           --subscribe status_observer volume_change system_woke power_source_change \
           --set status_observer width=0 \
                                 update_freq=10 \
                                 icon.drawing=off \
                                 label.drawing=off \
                                 script="$PLUGIN_DIR/status.sh"

sketchybar --add item weather q \
           --set weather update_freq=1800 \
                         icon.padding_right=4 \
                         label.padding_left=0 \
                         label.padding_right=16 \
                         script="$PLUGIN_DIR/weather.sh" \
           --add item clock e \
           --set clock update_freq=10 \
                       icon.drawing=off \
                       label.padding_left=16 \
                       label.padding_right=8 \
                       script="$PLUGIN_DIR/clock.sh"

sketchybar --update
