[tools]
bun = "latest"
go = "latest"
gradle = "latest"
java = "latest"
node = "lts"
python = "latest"
ruby = "latest"
rust = "latest"

[settings.github]
credential_command = 'gh auth token --hostname "$MISE_CREDENTIAL_HOST"'
use_git_credentials = true
